services:
  postgres:
    image: postgres:16
    container_name: fp-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fraud
    ports:
      - "${PG_PORT:-5543}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: fp-redis
    ports:
      - "${REDIS_PORT:-6380}:6379"
    restart: unless-stopped

  kafka:
    image: apache/kafka:3.8.1
    container_name: fp-kafka
    hostname: kafka
    ports:
      - "${KAFKA_OUTSIDE_PORT:-9094}:9094"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,PLAINTEXT_HOST://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9094
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
      CLUSTER_ID: aaaaaaaaaaaaaaaaaaaaaa
    volumes:
      - kafkadata:/var/lib/kafka/data
    restart: unless-stopped

  # one-shot helper to create topics at startup
  kafka-init:
    image: apache/kafka:3.8.1
    container_name: fp-kafka-init
    depends_on:
      - kafka
    entrypoint: ["/bin/bash","-c"]
    command:
      - |
        echo 'Waiting for Kafka...' && sleep 10
        /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists --topic payments.events --partitions 3 --replication-factor 1
        /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists --topic fraud.decisions --partitions 3 --replication-factor 1
        /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists --topic payments.dlq --partitions 1 --replication-factor 1
        echo 'Kafka topics created.'
    restart: "no"

  kafka-exporter:
    image: danielqsj/kafka-exporter:v1.7.0
    container_name: fp-kafka-exporter
    depends_on:
      - kafka
    environment:
      KAFKA_SERVER: kafka:9092
    ports:
      - "9308:9308"
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.53.0
    container_name: fp-prometheus
    depends_on:
      - kafka-exporter
    ports:
      - "9090:9090"
    volumes:
      - ./ops/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    restart: unless-stopped

  grafana:
    image: grafana/grafana:10.4.3
    container_name: fp-grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_DASHBOARDS_MIN_REFRESH_INTERVAL: 5s
    volumes:
      - ./ops/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./ops/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./ops/grafana/dashboards:/var/lib/grafana/dashboards:ro
    restart: unless-stopped

volumes:
  pgdata:
  kafkadata:
