global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: ingest-api
    static_configs:
      - targets: ["host.docker.internal:8080"]
  - job_name: fraud-service
    static_configs:
      - targets: ["host.docker.internal:8082"]
  - job_name: alerts-service
    static_configs:
      - targets: ["host.docker.internal:8083"]
  - job_name: kafka
    static_configs:
      - targets: ["kafka-exporter:9308"]
